
// common
const CHANGE_CURRENT_MODULE_TYPE = 'CHANGE_CURRENT_MODULE_TYPE'
const SET_SEARCH_DATA = 'SET_SEARCH_DATA'

// book
const SET_CURRENT_BOOK_TAGS = 'SET_CURRENT_BOOK_TAGS'
const SET_CURRENT_BOOK_TAG = 'SET_CURRENT_BOOK_TAG'
const SET_TAG_BOOKS = 'SET_TAG_BOOKS'
const SET_CURRENT_TAG_BOOKS = 'SET_CURRENT_TAG_BOOKS'
const SET_CURRENT_BOOK_TYPE = 'SET_CURRENT_BOOK_TYPE'
const SET_TYPE_BOOKS = 'SET_TYPE_BOOKS'
const SET_CURRENT_TYPE_BOOKS = 'SET_CURRENT_TYPE_BOOKS'

export {
  CHANGE_CURRENT_MODULE_TYPE,
  SET_SEARCH_DATA,
  SET_CURRENT_BOOK_TAGS,
  SET_CURRENT_BOOK_TAG,
  SET_TAG_BOOKS,
  SET_CURRENT_TAG_BOOKS,
  SET_CURRENT_BOOK_TYPE,
  SET_TYPE_BOOKS,
  SET_CURRENT_TYPE_BOOKS
}
